name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - name: "CLA Assistant"
        if: ( github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' || github.event_name == 'pull_request_target' ) && github.repository == 'Olsc/ManorBrowser'
        # Beta Release
        uses: cla-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: ".github/signatures/cla.json"
          path-to-document: "https://github.com/Olsc/ManorBrowser/blob/main/.github/ContributorLicenseAgreement.md" # e.g. a CLA or a DCO document
          # branch should not be protected - change this to a non-protected branch if needed
          branch: "cla-signatures"
          allowlist: Olsc,bot*
          use-dco-flag: false
          lock-pullrequest-aftermerge: true
          suggest-recheck: true